apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iotp3-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iotp3-application.git"
    targetRevision: master
    path: manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
