Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.boot_timeout = 600

  config.vm.define "ahuberS" do |server|
    server.vm.hostname = "ahuberS"
    server.vm.network "private_network", ip: "192.168.56.110"

    config.hostsupdater.aliases = [
      "app1.com",
      "app2.com",
      "app3.com"
    ]

    server.vm.provider "virtualbox" do |vb|
      vb.name = "ahuberS"
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.synced_folder "./pods-cfg", "/pods-cfg", type: "virtualbox"

    server.vm.provision "shell", path: "server.sh"
  end
end
